import { test } from "node:test";
import assert from "node:assert/strict";
import { buildMigrationDoc } from "../src/migration-doc.js";
import type { MigrationDocInput } from "../src/migration-doc.js";

const sample: MigrationDocInput = {
  files: [
    {
      file: "src/Form.tsx",
      manual: [
        {
          component: "Autocomplete",
          line: 42,
          message:
            "Autocomplete -> shadcn Combobox; build it manually (shadcn add command popover button)",
        },
      ],
      warnings: ["line 12 <Select>: onChange becomes onValueChange"],
    },
    {
      file: "src/Toolbar.tsx",
      manual: [{ component: "SpeedDial", line: 8, message: "SpeedDial has no equivalent; use DropdownMenu" }],
      warnings: [],
    },
  ],
  components: ["button", "command", "popover"],
  base: "base",
  version: "0.3.0",
  generatedAt: "2026-06-18",
};

test("doc has header, provenance, per-file tasks, and the install command", () => {
  const doc = buildMigrationDoc(sample);
  assert.match(doc, /^# Migration tasks — MUI → shadcn\/ui/);
  assert.match(doc, /mui-to-shadcn v0\.3\.0 on 2026-06-18/);
  // grouped by file, with line + component + the verbatim recipe message
  assert.match(doc, /### src\/Form\.tsx/);
  assert.match(doc, /\*\*L42\*\* `<Autocomplete>`/);
  assert.match(doc, /shadcn add command popover button/);
  assert.match(doc, /### src\/Toolbar\.tsx/);
  assert.match(doc, /\*\*L8\*\* `<SpeedDial>`/);
  // install command lists the required slugs
  assert.match(doc, /pnpm dlx shadcn@latest add button command popover/);
  // counts: 2 tasks across 2 files, 1 review note
  assert.match(doc, /## Open \/ broken \(2 tasks in 2 files\)/);
  assert.match(doc, /## Review — auto-changes to verify \(1 note\)/);
  assert.match(doc, /onChange becomes onValueChange/);
});

test("Base UI rules appear only for --base base", () => {
  const baseUi = buildMigrationDoc(sample);
  assert.match(baseUi, /Base UI specifics/);
  assert.match(baseUi, /shadcn\/ui \(Base UI variant\)/);

  const radix = buildMigrationDoc({ ...sample, base: "radix" });
  assert.doesNotMatch(radix, /Base UI specifics/);
  assert.match(radix, /shadcn\/ui \(Radix variant\)/);
});

test("warnings-only run still produces a full doc with a populated Review section", () => {
  const doc = buildMigrationDoc({
    ...sample,
    files: [
      { file: "src/Page.tsx", manual: [], warnings: ["createTheme is not converted; port tokens to Tailwind"] },
    ],
  });
  assert.match(doc, /## Open \/ broken\n\nNone/);
  assert.doesNotMatch(doc, /\*\*L\d+\*\*/); // no task bullets
  assert.match(doc, /## Review — auto-changes to verify/);
  assert.match(doc, /createTheme is not converted/);
  assert.doesNotMatch(doc, /Nothing left to migrate or review/);
});

test("empty run says nothing to do and emits no task list", () => {
  const doc = buildMigrationDoc({ ...sample, files: [] });
  assert.match(doc, /Nothing left to migrate or review/);
  assert.doesNotMatch(doc, /## Open \/ broken/);
  assert.doesNotMatch(doc, /\*\*L\d+\*\*/);
});

test("missing version omits the version from the provenance line", () => {
  const doc = buildMigrationDoc({ ...sample, version: "" });
  assert.match(doc, /Generated by mui-to-shadcn on 2026-06-18/);
  assert.doesNotMatch(doc, /mui-to-shadcn v on/);
});

test("a manual component is not echoed into the Review section", () => {
  const doc = buildMigrationDoc({
    ...sample,
    files: [
      {
        file: "src/X.tsx",
        manual: [{ component: "SpeedDial", line: 9, message: "SpeedDial has no equivalent; use DropdownMenu" }],
        warnings: [
          "line 9 <SpeedDial>: SpeedDial has no equivalent; use DropdownMenu", // echo of the manual hit
          "line 3 <Select>: onChange becomes onValueChange", // genuine review note
        ],
      },
    ],
  });
  assert.match(doc, /\*\*L9\*\* `<SpeedDial>`/); // task listed once
  assert.match(doc, /## Review — auto-changes to verify \(1 note\)/); // echo dropped, genuine note kept
  assert.match(doc, /onChange becomes onValueChange/);
  assert.doesNotMatch(doc, /- line 9 <SpeedDial>:/);
});
