import type { ManualHit } from "./plan.js";

export interface FileReport {
  /** Path shown to the reader (relative to the cwd in CLI use). */
  file: string;
  /** Components the codemod could not convert on its own. */
  manual: ManualHit[];
  /** Auto-changes that may need a human/LLM check. */
  warnings: string[];
}

export interface MigrationDocInput {
  /** Only files that have at least one manual hit or warning. */
  files: FileReport[];
  /** Required shadcn component slugs (sorted). */
  components: string[];
  /** Target variant — changes the Base UI rules emitted for the assistant. */
  base: "radix" | "base";
  /** Tool version, e.g. "0.3.0". Empty string if unknown. */
  version: string;
  /** Generation date as YYYY-MM-DD (passed in so output stays deterministic). */
  generatedAt: string;
}

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? "" : "s"}`;
}

function provenance(version: string, date: string): string {
  const v = version ? ` v${version}` : "";
  return `_Generated by mui-to-shadcn${v} on ${date}._`;
}

/**
 * A manual component emits both a manual hit and a paired warning
 * ("line N <Tag>: …") from the plan layer. Drop that warning from the Review
 * list so it isn't repeated — the Open/broken task already carries it.
 */
function isManualEcho(warning: string, manual: ManualHit[]): boolean {
  return manual.some(
    (hit) =>
      warning.endsWith(`: ${hit.message}`) ||
      (hit.message.includes("not in the registry") &&
        warning.startsWith(`line ${hit.line} `) &&
        warning.includes("not in the registry")),
  );
}

/**
 * Render an LLM-ready handoff document from a migration run. Pure and
 * deterministic: the same input always produces the same Markdown.
 */
export function buildMigrationDoc(input: MigrationDocInput): string {
  const { components, base, version, generatedAt } = input;
  const files = input.files
    .map((f) => ({ ...f, warnings: f.warnings.filter((w) => !isManualEcho(w, f.manual)) }))
    .sort((a, b) => a.file.localeCompare(b.file));

  const out: string[] = [];
  out.push("# Migration tasks — MUI → shadcn/ui");
  out.push("");
  out.push(provenance(version, generatedAt));
  out.push("");

  if (files.length === 0) {
    out.push("Nothing left to migrate or review 🎉 — the codemod converted everything it found.");
    out.push("");
    return out.join("\n");
  }

  const taskFiles = files.filter((f) => f.manual.length > 0);
  const reviewFiles = files.filter((f) => f.warnings.length > 0);
  const taskCount = taskFiles.reduce((sum, f) => sum + f.manual.length, 0);
  const reviewCount = reviewFiles.reduce((sum, f) => sum + f.warnings.length, 0);

  // ── Context block, addressed directly to the assistant ──
  out.push("## Your task");
  out.push("");
  out.push(
    "You are finishing a partial migration from Material UI (MUI) to shadcn/ui in this codebase. " +
      "The codemod has already converted the mechanical parts and rewritten the imports; your job is to resolve what it could not do automatically:",
  );
  out.push("");
  out.push(
    "1. Complete every item under **Open / broken** — each names the file, line, and MUI component, plus what it needs.",
  );
  out.push("2. Then check each item under **Review** — those were converted automatically but may need a fix.");
  out.push("");
  out.push("Rules:");
  out.push("");
  const variant = base === "base" ? "Base UI" : "Radix";
  out.push(
    `- Target stack: shadcn/ui (${variant} variant) + Tailwind CSS v4. Import components from \`@/components/ui/*\`.`,
  );
  out.push(
    "- Never reintroduce `@mui/*`, `@emotion/*`, or `@mui/icons-material` imports. Icons come from `lucide-react`.",
  );
  out.push("- Preserve the original behavior — if a prop was dropped, re-implement its effect rather than lose it.");
  out.push(
    '- Use the public shadcn API: `onValueChange`/`onCheckedChange`, `type="single|multiple"`, `AccordionItem`, etc.',
  );
  if (base === "base") {
    out.push(
      "- Base UI specifics: replace `asChild` with the render prop; `checked` is strictly boolean and `value` strictly an array; the Base UI `Select` needs an `items` prop on the root and `nativeButton={false}` on non-button triggers.",
    );
  }
  out.push("- Open each file at the given line and keep edits local; don't reformat unrelated code.");
  out.push("");

  // ── Install ──
  if (components.length > 0) {
    out.push("## Install the shadcn components first");
    out.push("");
    out.push("```bash");
    out.push(`pnpm dlx shadcn@latest add ${components.join(" ")}`);
    out.push("```");
    out.push("");
    if (taskCount > 0) {
      out.push("Some tasks below need extra shadcn components or packages — those are noted inline in the task.");
      out.push("");
    }
  }

  // ── Open / broken ──
  if (taskCount > 0) {
    out.push(`## Open / broken (${plural(taskCount, "task")} in ${plural(taskFiles.length, "file")})`);
    out.push("");
    for (const f of taskFiles) {
      out.push(`### ${f.file}`);
      out.push("");
      const hits = [...f.manual].sort((a, b) => a.line - b.line);
      for (const hit of hits) {
        out.push(`- **L${hit.line}** \`<${hit.component}>\` — ${hit.message}`);
      }
      out.push("");
    }
  } else {
    out.push("## Open / broken");
    out.push("");
    out.push("None — every component the codemod recognized was converted. ✅");
    out.push("");
  }

  // ── Review (secondary; omitted entirely when there's nothing to verify) ──
  if (reviewCount > 0) {
    out.push(`## Review — auto-changes to verify (${plural(reviewCount, "note")})`);
    out.push("");
    out.push("The codemod made these changes automatically. Confirm they behave like the MUI original.");
    out.push("");
    for (const f of reviewFiles) {
      out.push(`### ${f.file}`);
      out.push("");
      for (const warning of f.warnings) {
        out.push(`- ${warning}`);
      }
      out.push("");
    }
  }

  return out.join("\n");
}
